### ISSUE TITLE
PH3: Doc Review

### ISSUE THREAD

**Issue by rslruiz** [SEBASTIANSANTO/mp21ProjRecceri#1]
- Add more details and content in github
- Document still needs more information in it. Given references are good and shows what could the research contain in the future. This would cause them to add few more references since changes may happen as they do the project.

**Comment by SEBASTIANSANTO** [comment]
- Add more details and content in github (In-Progress)
- Document still needs more information in it. Given references are good and shows what could the research contain in the future. This would cause them to add few more references since changes may happen as they do the project. (Pending, will start after first issue has been Completed)
